### ISSUE TITLE
in UE5.3 only, hands are glitched with downloaded avatars only

### ISSUE THREAD

**Issue by jimsimonz** [readyplayerme/rpm-unreal-sdk#36]
With UE5.3 the skin on hand bones appear glitched when applying mixamo animations.
The hands look fine applying the same animations to the built in example skeleton, but as soon as a downloaded model is applied, the hands are glitched.

Glitched ( was fine with UE 5.2) :
![Glitched](https://github.com/readyplayerme/rpm-unreal-sdk/assets/3593208/21afed59-1530-4437-b4ca-2f92dc35eb78)

same anims with the built in skeleton/mesh (still UE5.3):
![BeforeDownload](https://github.com/readyplayerme/rpm-unreal-sdk/assets/3593208/751569e2-66bb-473f-8c3a-31bcd561b62d)

This looks like an Epic bug with their animation mapping to different meshes though the downloaded example should be the same as the example that comes with the RPM plugin.

Any ideas on this?

**Comment by jimsimonz** [comment]
thanks for the update

**Comment by gadamyan** [comment]
This bug is fixed in the latest version of the glTFRuntime library. Please update the glTFRuntime library to the latest version, remove all the generated files, and try again.

**Comment by jimsimonz** [comment]
Hi. unfortunately the latest glTFRuntime build pulled from Master didn't fix it. I'll do some more investigating and get back if I find anything useful.

**Comment by jimsimonz** [comment]
I've tried with no animations and it's still the same,  so on loading a downloaded asset, finger joints are getting skinned wrong somehow.

**Comment by gadamyan** [comment]
I think we found what is causing the issue. This line is causing the issue.
SkeletalMeshConfig.MaterialsConfig.bMergeSectionsByMaterial
We will try to understand how to fix it.
For now, you can just set it to false, until we try to fix it.

**Comment by gadamyan** [comment]
The issue is fixed in the SDK release 1.4.4
